#!/bin/sh

set -e

# Use hombrew's ctags if available
export PATH=/usr/local/bin:$PATH

command -v ctags > /dev/null 2>&1 || exit 0

trap "rm -f .git/tags.$$" EXIT

rm -f .git/tags
ctags \
  --tag-relative -Rf.git/tags.$$ \
  --exclude=.git \
  --languages=-javascript,sql

mv .git/tags.$$ .git/tags
