#!/bin/sh

# Reference: https://macos-defaults.com/

nuke() {
  command killall "$1" >/dev/null 2>&1
}


# Disable the "Are you sure you want to open this application?" dialog.
defaults write com.apple.LaunchServices "LSQuarantine" -bool "false"


# Always open new documents in tabs.
defaults write NSGlobalDomain "AppleWindowTabbingMode" "always"


# Keyboard
defaults write NSGlobalDomain "KeyRepeat" -int "2"
defaults write NSGlobalDomain "InitialKeyRepeat" -int "15"


# Expand print panel by default.
defaults write NSGlobalDomain "NSNavPanelExpandedStateForPrintMode" -bool "true"
defaults write NSGlobalDomain "NSNavPanelExpandedStateForPrintMode2" -bool "true"

# Expand save panel by default.
defaults write NSGlobalDomain "NSNavPanelExpandedStateForSaveMode" -bool "true"
defaults write NSGlobalDomain "NSNavPanelExpandedStateForSaveMode2" -bool "true"


# Text correction
defaults write NSGlobalDomain "NSAutomaticCapitalizationEnabled" -bool "false"      # Disable automatic capitalization.
defaults write NSGlobalDomain "NSAutomaticPeriodSubstitutionEnabled" -bool "false"  # Disable peroid substitution.
defaults write NSGlobalDomain "NSAutomaticQuoteSubstitutionEnabled" -bool "false"   # Disable smart quotes.
defaults write NSGlobalDomain "NSAutomaticDashSubstitutionEnabled" -bool "false"    # Disable smart dashes.
defaults write NSGlobalDomain "NSAutomaticCapitalizationEnabled" -bool "false"      # Disable automatic capitalization.
defaults write NSGlobalDomain "NSAutomaticSpellingCorrectionEnabled" -bool "false"  # Disable auto-correct.
defaults write NSGlobalDomain "NSAutomaticTextCompletionEnabled" -bool "false"      # Disable text-completion.


# Set default to plain text in TextEdit
defaults write com.apple.TextEdit "RichText" -bool "true"

# Quotes will remain in the form they are typed
defaults write com.apple.TextEdit "SmartQuotes" -bool "false"


# Put the Dock on the left of the screen
defaults write com.apple.dock "orientation" -string "left"

# Autohide the Dock when the mouse is out
defaults write com.apple.dock "autohide" -bool "true"

# Remove the autohide delay, the Dock appears instantly
defaults write com.apple.dock "autohide-delay" -float "0"

# Remove the Dock autohide animation
defaults write com.apple.dock "autohide-time-modifier" -float "0"

# Do not display recent apps in the Dock
defaults write com.apple.dock "show-recents" -bool "false"

# Minimize does scale animation
defaults write com.apple.dock "mineffect" -string "scale"

# Restart dock
nuke Dock


# Safari: Show full website URL
defaults write com.apple.safari "ShowFullURLInSmartSearchField" -bool "true"

# Restart Safari
nuke Safari


# Display the Finder "Quit" option
defaults write com.apple.finder "QuitMenuItem" -bool "true"

# Set default location for new Finder windows
# Computer     : `PfCm`
# Volume       : `PfVo`
# $HOME        : `PfHm`
# Desktop      : `PfDe`
# Documents    : `PfDo`
# All My Files : `PfAF`
# Other…       : `PfLo`
defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

# Show all file extensions inside the Finder
defaults write NSGlobalDomain "AppleShowAllExtensions" -bool "true"

# Show hidden files inside the Finder
defaults write com.apple.finder "AppleShowAllFiles" -bool "true"

# Add pathbar to bottom of Finder
defaults write com.apple.finder "ShowPathbar" -bool "true"

# Add statusbar to bottom of Finder
defaults write com.apple.finder "ShowStatusBar" -bool "true"

# Set preferred view style.
# Icon View   : `icnv`
# List View   : `Nlsv`
# Column View : `clmv`
# Cover Flow  : `Flwv`
defaults write com.apple.finder "FXPreferredViewStyle" -string "Nlsv"

# Keep folders on top when searching by name
defaults write com.apple.finder "_FXSortFoldersFirst" -bool "true"

# Default to searching the current folder
defaults write com.apple.finder "FXDefaultSearchScope" -string "SCcf"

# Do not display the warning when changing file extension
defaults write com.apple.finder "FXEnableExtensionChangeWarning" -bool "false"

# Remove the delay when hovering the toolbar title
defaults write NSGlobalDomain "NSToolbarTitleViewRolloverDelay" -float "0"

# Desktop: keep folders on top
defaults write com.apple.finder "_FXSortFoldersFirstOnDesktop" -bool "true"

# Restart 
nuke Finder


# Key auto-repeat enabled
defaults write NSGlobalDomain "ApplePressAndHoldEnabled" -bool "false"


# Short key repeat delay
defaults write com.apple.Accessibility "KeyRepeatDelay" -float "0.5"

# Faster key repeat speed
defaults write com.apple.Accessibility "KeyRepeatInterval" -float "0.083333333"


# Remap capslock to control
#
# Keycodes:
#   https://developer.apple.com/library/archive/technotes/tn2450/_index.html#//apple_ref/doc/uid/DTS40017618-CH1-KEY_TABLE_USAGES
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc": 0x700000039, "HIDKeyboardModifierMappingDst": 0x7000000E0}]}'

