# TODO:
# https://bitbucket.org/nishigori/dotfiles/src
#   Alignta mappings
# https://github.com/bling/vim-bufferline
# https://github.com/bling/vim-airline
# https://github.com/fholgado/minibufexpl.vim
#
# https://github.com/nelstrom/dotfiles/
# https://github.com/sfowler/dot-vim/tree/master/bundle
# 
# https://github.com/travitch/hasksyn

load "plugins.rake"

def is_windows?
  @is_windows ||= !!(RbConfig::CONFIG['host_os'] =~ /windows/i)
end

### CORE

# fast file navigation
#plugin "command-t", "https://github.com/wincent/Command-T.git" do
  #sh "cd ruby/command-t && ruby extconf.rb && make clean && make"
#end

# Too distracting...
# plugin "indentLine", "https://github.com/Yggdroot/indentLine.git"

# http://bling.github.io//blog/2013/06/02/unite-dot-vim-the-plugin-you-didnt-know-you-need/
# https://github.com/basyura/unite-rails
# https://github.com/rhysd/unite-ruby-require.vim
# https://github.com/ujihisa/unite-rake
# https://github.com/tacroe/unite-mark
# https://github.com/tsukkee/unite-tag
# plugin "unite", "https://github.com/Shougo/unite.vim"
# plugin "unite-ssh", "https://github.com/Shougo/unite-ssh"
# plugin "vimfiler", "https://github.com/Shougo/vimfiler.vim"
# plugin "vimfiler-preview", "https://github.com/itchyny/vimfiler-preview"

plugin "ctrlp", "https://github.com/kien/ctrlp.vim.git"

# project tree navigation
plugin "nerdtree", "https://github.com/scrooloose/nerdtree.git"

# search in project
plugin "ack", "https://github.com/mileszs/ack.vim.git"
plugin "ag", "https://github.com/rking/ag.vim.git"

# ctags file management
#plugin "autotag", "https://github.com/vim-scripts/AutoTag.git"
#plugin "tagbar", "https://github.com/majutsushi/tagbar.git"

plugin "eunuch", "https://github.com/tpope/vim-eunuch.git"

# asynchronous build and test dispatcher
plugin "dispatch", "https://github.com/tpope/vim-dispatch.git"

plugin "alternate"  do
  mkdir_p "plugin"
  sh "curl 'http://www.vim.org/scripts/download_script.php?src_id=7218' > plugin/a.vim"
end

plugin "scratch" do
  mkdir_p "plugin"
  sh "curl 'http://www.vim.org/scripts/download_script.php?src_id=2050' > plugin/scratch.vim"
end

plugin "vimwiki", "https://github.com/vimwiki/vimwiki.git"

# VimOutliner:
# http://www.vim.org/scripts/script.php?script_id=3515

# http://www.vim.org/scripts/script.php?script_id=2657
#plugin "voom" do
#  mkdir_p "voom"
#  sh "curl 'http://www.vim.org/scripts/download_script.php?src_id=19447' > plugin/voom.zip"
#  sh "unzip plugin/voom.zip"
#  sh "rm plugin/voom.zip"
#end

### EDITING AND MOVING

# after hooks for colorschemes
#plugin "aftercolors", "https://github.com/vim-scripts/AfterColors.vim.git"

# color schemes
plugin "solarized", "https://github.com/altercation/vim-colors-solarized.git"
plugin "tomorrow-night", "https://github.com/chriskempson/vim-tomorrow-theme.git"
plugin "base16", "https://github.com/chriskempson/base16-vim.git"
plugin "vim-mac-classic-theme", "https://github.com/nelstrom/vim-mac-classic-theme"
plugin "jellybeans", "https://github.com/nanotech/jellybeans.vim.git"
plugin "jellyx", "https://github.com/guns/jellyx.vim.git"
plugin "hybrid", "https://github.com/w0ng/vim-hybrid.git"
plugin "xoria256" do
  mkdir_p "colors"
  sh "curl 'http://www.vim.org/scripts/download_script.php?src_id=15762' > colors/xoria256.vim"
end

# code commenting
plugin "nerdcommenter", "https://github.com/scrooloose/nerdcommenter.git"

# pairs of surroundings
plugin "surround", "https://github.com/tpope/vim-surround.git"

# automatically add "end" to ruby, vimscript, and more
plugin "endwise", "https://github.com/tpope/vim-endwise.git"

# show colors in css files, including hsl and rgb
# plugin "vim-css-color", "https://github.com/ap/vim-css-color.git"

# highlight matching html tags
plugin "matchtag", "https://github.com/gregsexton/MatchTag.git"

# '.' repetition support for plugins
plugin "vim-repeat", "https://github.com/tpope/vim-repeat.git"

# 'ai' "an indent" 'ii' "inside indent" mappings
plugin "indent-object", "https://github.com/michaeljsmith/vim-indent-object.git"

# a variety of bracket mappings, including line bubbling
plugin "unimpaired", "https://github.com/tpope/vim-unimpaired.git"

# automatic syntax checking
plugin "syntastic", "https://github.com/scrooloose/syntastic.git"

# extended matching for %
plugin "matchit", "https://github.com/edsono/vim-matchit.git"

# merge tabs together
plugin "tabmerge" do
  mkdir_p "plugin"
  sh "curl 'http://www.vim.org/scripts/download_script.php?src_id=8828' > plugin/Tabmerge.vim"
end

# align vs tabular plugins
# plugin "tabular", "https://github.com/godlygeek/tabular.git"
plugin "align", "https://github.com/tsaleh/vim-align.git"

# snippets
plugin "snipmate", "https://github.com/garbas/vim-snipmate.git"
plugin "vim-snippets", "https://github.com/honza/vim-snippets.git"

# snipmate dependencies
plugin "tlib", "https://github.com/tomtom/tlib_vim.git"
plugin "addon-mw-utils", "https://github.com/MarcWeber/vim-addon-mw-utils.git"

# fast autocomplete
# plugin "neocomplcache", "https://github.com/Shougo/neocomplcache.git"
plugin "YouCompleteMe", "https://github.com/Valloric/YouCompleteMe.git" do
  sh "git submodule update --init --recursive"
  sh "./install.sh --clang-completer --omnisharp-completer"
end

# async execution, builds neocomplcache in the background
plugin "vimproc", "https://github.com/Shougo/vimproc.git" do
  sh "make -f make_mac.mak"
end

### LANGUAGE AND SYNTAX

# ruby language support
plugin "vim-ruby", "https://github.com/vim-ruby/vim-ruby.git"
# run ruby tests from inside vim
plugin "vim-vroom", "https://github.com/skalnik/vim-vroom.git"
# toggle between :symbol "string" 'string', and more
plugin "switch", "git://github.com/AndrewRadev/switch.vim.git"

# html/erb editing support
plugin "vim-ragtag", "https://github.com/tpope/vim-ragtag.git"

# CSharp (depends on vim-dispatch)
#plugin "omnisharp", "https://github.com/nosami/Omnisharp.git" do
#  cmd = is_windows? ?
#    'msbuild /p:Platform="Any CPU"' :
#    'xbuild  /p:Platform="Any CPU"'
#  sh 'git submodule update --init'
#  chdir 'server' do
#    sh cmd
#  end
#end

# NOTE: requires some set up - see https://github.com/Floobits/floobits-vim
# plugin "floobits", "https://github.com/Floobits/floobits-vim.git"

plugin "headerguard", "https://github.com/vim-scripts/headerguard.vim.git"
plugin "nginx-vim-syntax", "https://github.com/evanmiller/nginx-vim-syntax.git"
# plugin "csv", "https://github.com/vim-scripts/csv.vim.git"
plugin "haml", "https://github.com/tpope/vim-haml.git"
plugin "slim", "https://github.com/slim-template/vim-slim.git"
plugin "scss", "https://github.com/cakebaker/scss-syntax.vim.git"
plugin "less", "https://github.com/groenewege/vim-less.git"
plugin "html5", "git://github.com/othree/html5.vim.git"
plugin "html5-syntax", "git://github.com/othree/html5-syntax.vim.git"
plugin "nodejs", "https://github.com/mmalecki/vim-node.js.git"
plugin "javascript", "https://github.com/pangloss/vim-javascript.git"
plugin "jasmine", "https://github.com/claco/jasmine.vim.git"
plugin "jshint", "https://github.com/wookiehangover/jshint.vim.git"
plugin "liquid", "https://github.com/tpope/vim-liquid.git"
plugin "markdown", "https://github.com/tpope/vim-markdown.git"
plugin "textile", "https://github.com/timcharper/textile.vim.git"
plugin "puppet", "https://github.com/ajf/puppet-vim.git"
plugin "rake", "https://github.com/tpope/vim-rake.git"
plugin "bundler", "https://github.com/tpope/vim-bundler.git"
plugin "rails", "https://github.com/tpope/vim-rails.git"
plugin "rspec", "https://github.com/thoughtbot/vim-rspec"
plugin "cucumber", "https://github.com/tpope/vim-cucumber.git"
plugin "minitest", "https://github.com/sunaku/vim-ruby-minitest.git"
plugin "vimerl", "https://github.com/jimenezrick/vimerl.git"
plugin "elixer", "https://github.com/elixir-lang/vim-elixir.git"
plugin "elixer-snippets", "https://github.com/carlosgaldino/elixir-snippets.git"
plugin "scala", "https://github.com/derekwyatt/vim-scala.git"
plugin "sinatra", "https://github.com/hallison/vim-ruby-sinatra.git"
plugin "coffeescript", "https://github.com/AndrewRadev/vim-coffee-script.git"
plugin "vim-ls", "https://github.com/gkz/vim-ls.git"
plugin "handlebars", "https://github.com/nono/vim-handlebars.git"
plugin "mustache", "https://github.com/juvenn/mustache.vim.git"
plugin "nimrod", "https://github.com/zah/nimrod.vim.git"
plugin "rust", "https://github.com/wting/rust.vim.git"
plugin "eclim", "https://github.com/cstrahan/vim-eclim.git"
plugin "capnp", "https://github.com/cstrahan/vim-capnp.git"
plugin "golang", "https://github.com/jnwhiteh/vim-golang.git" # syntax
plugin "dockerfile", "https://github.com/ekalinin/Dockerfile.vim.git"
plugin "gocode", "https://github.com/Blackrush/vim-gocode.git" do # completion
  if is_windows?
    sh 'go get -u -ldflags -H=windowsgui github.com/nsf/gocode'
  else
    sh 'go get -u github.com/nsf/gocode'
  end
end


# auto-expand html
# plugin "sparkup", "https://github.com/kogakure/vim-sparkup.git"
plugin "zencoding", "https://github.com/mattn/zencoding-vim.git"

# Lisp/SWANK
# TODO: https://bitbucket.org/kovisoft/slimv

# clojure:
plugin "vim-classpath", "https://github.com/tpope/vim-classpath.git"
plugin "vim-clojure-static", "https://github.com/guns/vim-clojure-static.git"
plugin "vim-fireplace", "https://github.com/tpope/vim-fireplace.git"
plugin "vim-redl", "https://github.com/dgrnbrg/vim-redl.git"
# plugin "vim-sexp", "https://github.com/guns/vim-sexp.git"
# plugin "vim-sexp-mappings-for-regular-people", "https://github.com/tpope/vim-sexp-mappings-for-regular-people.git"

# NixOS/NixPKG
#   deps: "vim-addon-mw-utils", "tlib", "vim-addon-actions", "vim-addon-completion", "vim-addon-goto-thing-at-cursor"
# plugin "vim-addon-completion", "https://github.com/MarcWeber/vim-addon-completion.git"
# plugin "vim-addon-mw-utils", "https://github.com/MarcWeber/vim-addon-mw-utils.git"
# plugin "vim-addon-actions", "https://github.com/MarcWeber/vim-addon-actions.git"
# plugin "vim-addon-goto-thing-at-cursor", "https://github.com/MarcWeber/vim-addon-goto-thing-at-cursor.git"
# plugin "vim-addon-nix", "https://github.com/MarcWeber/vim-addon-nix.git"

# haskell:
# Hackage/doc integration
# plugin "haskellmode", "https://github.com/lukerandall/haskellmode-vim.git"
plugin "haskell-indent", "https://github.com/vim-scripts/indenthaskell.vim.git"
# haskell tools - show type of expression, syntax checking, lint, imports
plugin "html-template-syntax", "https://github.com/pbrisbin/html-template-syntax"
plugin "ghcmod", "https://github.com/eagletmt/ghcmod-vim.git"
plugin "vim-hdevtools", "https://github.com/bitc/vim-hdevtools" # supposedly faster than ghcmod
# haskell-aware auto-completion
plugin "neco-ghc", "https://github.com/ujihisa/neco-ghc.git"
# split-based hoogle search, as opposed to haskellmode's web based search
# https://github.com/Twinside/vim-hoogle
# Automatically generate Haskell tags
#https://github.com/bitc/lushtags
#https://github.com/ujihisa/unite-haskellimport
# haddock/hoogle integration
#plugin "unite-haddock", "https://github.com/eagletmt/unite-haddock"

### MISC

# TODO: try this out. figure out how background compilation works.
#plugin "LaTeX-Box", "https://github.com/LaTeX-Box-Team/LaTeX-Box.git"

#plugin "vim-powerline", "https://github.com/Lokaltog/vim-powerline.git"
#plugin "powerline", "https://github.com/Lokaltog/powerline.git"

# tmux/iTerm2 support
#let g:vitality_fix_focus = 1
#let g:vitality_fix_cursor = 1
#let g:vitality_always_assume_iterm = 1
#plugin "vitality", "https://github.com/aaronjensen/vitality.vim.git"

# readline style insertion
# plugin "vim-rsi", "https://github.com/tpope/vim-rsi.git"

# git support
plugin "fugitive", "https://github.com/tpope/vim-fugitive.git"
plugin "vim-git", "https://github.com/tpope/vim-git.git"
#plugin "gitv", "https://github.com/gregsexton/gitv.git"
#plugin "gitgutter", "https://github.com/airblade/vim-gitgutter.git"

# for using syntax-highlighted text in presentations
plugin "copy-as-rtf", "https://github.com/zerowidth/vim-copy-as-rtf.git"

# gist integration
plugin "gist-vim", "https://github.com/mattn/gist-vim.git"

# indexed search
plugin "vim-indexed-search", "https://github.com/henrik/vim-indexed-search.git"
