#!/bin/sh

# From the docs:
#   The following arguments are passed to the file
#     (1) current file name
#     (2) width
#     (3) height
#     (4) horizontal position, and
#     (5) vertical position of preview pane respectively.
#   SIGPIPE signal is sent when enough lines are read.
#   If the previewer returns a non-zero exit code, then the preview cache for the given file is disabled.
#   This means that if the file is selected in the future, the previewer is called once again.
#   Preview filtering is disabled and files are displayed as they are when the value of this option is left empty.

mime_preview() {
	case "$mime_type" in
    (image/svg+xml | image/svg)
      # TODO
      bat "$1"
      ;;
    (*)
      #bat "$1"
      bat --terminal-width "$(($4*7/9))" -f "$1" --style=numbers
      ;;
  esac
}

main() {
	mime_type="$(file --dereference -b --mime-type -- "$1")"
	mime_preview "$@" || return $?
}

main "$@" || exit $?

