
# : File-specific styles {{{

[filetype]

# colors taken from https://www.nordtheme.com/ports/dircolors
# generated via https://github.com/Mellbourn/lsColorsToToml
rules = [
  { name = "*/", fg = "blue", bold = true },
  { name = "*", is = "link", fg = "cyan" },
  { name = "*", is = "fifo", fg = "cyan", bold = true, underline = true },
  { name = "*", is = "sock", fg = "yellow", underline = true },
  { name = "*", is = "block", fg = "yellow", bold = true },
  { name = "*", is = "char", fg = "yellow" },
  { name = "*", is = "orphan", fg = "red" },
  { name = "*", is = "exec", fg = "cyan", bold = true },
  { name = "*", is = "sticky", fg = "gray", bg = "blue", underline = true },
  { name = "*.7z", fg = "green", bold = true },
  { name = "*.ace", fg = "green", bold = true },
  { name = "*.alz", fg = "green", bold = true },
  { name = "*.arc", fg = "green", bold = true },
  { name = "*.arj", fg = "green", bold = true },
  { name = "*.bz", fg = "green", bold = true },
  { name = "*.bz2", fg = "green", bold = true },
  { name = "*.cab", fg = "green", bold = true },
  { name = "*.cpio", fg = "green", bold = true },
  { name = "*.deb", fg = "green", bold = true },
  { name = "*.dz", fg = "green", bold = true },
  { name = "*.ear", fg = "green", bold = true },
  { name = "*.gz", fg = "green", bold = true },
  { name = "*.jar", fg = "green", bold = true },
  { name = "*.lha", fg = "green", bold = true },
  { name = "*.lrz", fg = "green", bold = true },
  { name = "*.lz", fg = "green", bold = true },
  { name = "*.lz4", fg = "green", bold = true },
  { name = "*.lzh", fg = "green", bold = true },
  { name = "*.lzma", fg = "green", bold = true },
  { name = "*.lzo", fg = "green", bold = true },
  { name = "*.rar", fg = "green", bold = true },
  { name = "*.rpm", fg = "green", bold = true },
  { name = "*.rz", fg = "green", bold = true },
  { name = "*.sar", fg = "green", bold = true },
  { name = "*.t7z", fg = "green", bold = true },
  { name = "*.tar", fg = "green", bold = true },
  { name = "*.taz", fg = "green", bold = true },
  { name = "*.tbz", fg = "green", bold = true },
  { name = "*.tbz2", fg = "green", bold = true },
  { name = "*.tgz", fg = "green", bold = true },
  { name = "*.tlz", fg = "green", bold = true },
  { name = "*.txz", fg = "green", bold = true },
  { name = "*.tz", fg = "green", bold = true },
  { name = "*.tzo", fg = "green", bold = true },
  { name = "*.tzst", fg = "green", bold = true },
  { name = "*.war", fg = "green", bold = true },
  { name = "*.xz", fg = "green", bold = true },
  { name = "*.z", fg = "green", bold = true },
  { name = "*.Z", fg = "green", bold = true },
  { name = "*.zip", fg = "green", bold = true },
  { name = "*.zoo", fg = "green", bold = true },
  { name = "*.zst", fg = "green", bold = true },
  { name = "*.aac", fg = "green" },
  { name = "*.au", fg = "green" },
  { name = "*.flac", fg = "green" },
  { name = "*.m4a", fg = "green" },
  { name = "*.mid", fg = "green" },
  { name = "*.midi", fg = "green" },
  { name = "*.mka", fg = "green" },
  { name = "*.mp3", fg = "green" },
  { name = "*.mpa", fg = "green" },
  { name = "*.mpeg", fg = "green" },
  { name = "*.mpg", fg = "green" },
  { name = "*.ogg", fg = "green" },
  { name = "*.opus", fg = "green" },
  { name = "*.ra", fg = "green" },
  { name = "*.wav", fg = "green" },
  { name = "*.3des", fg = "magenta", bold = true },
  { name = "*.aes", fg = "magenta", bold = true },
  { name = "*.gpg", fg = "magenta", bold = true },
  { name = "*.pgp", fg = "magenta", bold = true },
  { name = "*.doc", fg = "green" },
  { name = "*.docx", fg = "green" },
  { name = "*.dot", fg = "green" },
  { name = "*.odg", fg = "green" },
  { name = "*.odp", fg = "green" },
  { name = "*.ods", fg = "green" },
  { name = "*.odt", fg = "green" },
  { name = "*.otg", fg = "green" },
  { name = "*.otp", fg = "green" },
  { name = "*.ots", fg = "green" },
  { name = "*.ott", fg = "green" },
  { name = "*.pdf", fg = "green" },
  { name = "*.ppt", fg = "green" },
  { name = "*.pptx", fg = "green" },
  { name = "*.xls", fg = "green" },
  { name = "*.xlsx", fg = "green" },
  { name = "*.app", fg = "cyan", bold = true },
  { name = "*.bat", fg = "cyan", bold = true },
  { name = "*.btm", fg = "cyan", bold = true },
  { name = "*.cmd", fg = "cyan", bold = true },
  { name = "*.com", fg = "cyan", bold = true },
  { name = "*.exe", fg = "cyan", bold = true },
  { name = "*.reg", fg = "cyan", bold = true },
  { name = "*.bak", fg = "gray" },
  { name = "*.BAK", fg = "gray" },
  { name = "*.log", fg = "gray" },
  { name = "*.log", fg = "gray" },
  { name = "*.old", fg = "gray" },
  { name = "*.OLD", fg = "gray" },
  { name = "*.orig", fg = "gray" },
  { name = "*.ORIG", fg = "gray" },
  { name = "*.swo", fg = "gray" },
  { name = "*.swp", fg = "gray" },
  { name = "*.bmp", fg = "green" },
  { name = "*.cgm", fg = "green" },
  { name = "*.dl", fg = "green" },
  { name = "*.dvi", fg = "green" },
  { name = "*.emf", fg = "green" },
  { name = "*.eps", fg = "green" },
  { name = "*.gif", fg = "green" },
  { name = "*.jpeg", fg = "green" },
  { name = "*.jpg", fg = "green" },
  { name = "*.JPG", fg = "green" },
  { name = "*.mng", fg = "green" },
  { name = "*.pbm", fg = "green" },
  { name = "*.pcx", fg = "green" },
  { name = "*.pgm", fg = "green" },
  { name = "*.png", fg = "green" },
  { name = "*.PNG", fg = "green" },
  { name = "*.ppm", fg = "green" },
  { name = "*.pps", fg = "green" },
  { name = "*.ppsx", fg = "green" },
  { name = "*.ps", fg = "green" },
  { name = "*.svg", fg = "green" },
  { name = "*.svgz", fg = "green" },
  { name = "*.tga", fg = "green" },
  { name = "*.tif", fg = "green" },
  { name = "*.tiff", fg = "green" },
  { name = "*.xbm", fg = "green" },
  { name = "*.xcf", fg = "green" },
  { name = "*.xpm", fg = "green" },
  { name = "*.xwd", fg = "green" },
  { name = "*.xwd", fg = "green" },
  { name = "*.yuv", fg = "green" },
  { name = "*.anx", fg = "green" },
  { name = "*.asf", fg = "green" },
  { name = "*.avi", fg = "green" },
  { name = "*.axv", fg = "green" },
  { name = "*.flc", fg = "green" },
  { name = "*.fli", fg = "green" },
  { name = "*.flv", fg = "green" },
  { name = "*.gl", fg = "green" },
  { name = "*.m2v", fg = "green" },
  { name = "*.m4v", fg = "green" },
  { name = "*.mkv", fg = "green" },
  { name = "*.mov", fg = "green" },
  { name = "*.MOV", fg = "green" },
  { name = "*.mp4", fg = "green" },
  { name = "*.mpeg", fg = "green" },
  { name = "*.mpg", fg = "green" },
  { name = "*.nuv", fg = "green" },
  { name = "*.ogm", fg = "green" },
  { name = "*.ogv", fg = "green" },
  { name = "*.ogx", fg = "green" },
  { name = "*.qt", fg = "green" },
  { name = "*.rm", fg = "green" },
  { name = "*.rmvb", fg = "green" },
  { name = "*.swf", fg = "green" },
  { name = "*.vob", fg = "green" },
  { name = "*.webm", fg = "green" },
  { name = "*.wmv", fg = "green" },
]

# : }}}
