#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then
  exec reattach-to-user-namespace pbcopy

elif command -v xsel >/dev/null 2>&1; then
  exec xsel -i -b

elif command -v xclip >/dev/null 2>&1; then
  exec xclip -i -selection clipboard

fi
